name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, i686-unknown-linux-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for i686 target (32-bit Linux only)
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: List files after build
        run: |
          echo "Listing files in target/${{ matrix.target }}/release:"
          ls -al target/${{ matrix.target }}/release/

      - name: Create tar.gz package
        run: |
          mkdir -p artifacts/${{ matrix.target }}
          tar -czvf artifacts/${{ matrix.target }}/http-proxy-ipv6-pool_${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release http-proxy-ipv6-pool

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-release
          path: artifacts/${{ matrix.target }}/http-proxy-ipv6-pool_${{ matrix.target }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download x86_64 artifacts
        uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu-release
          path: ./artifacts/x86_64

      - name: Download i686 artifacts
        uses: actions/download-artifact@v3
        with:
          name: i686-unknown-linux-gnu-release
          path: ./artifacts/i686

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/x86_64/http-proxy-ipv6-pool_x86_64-unknown-linux-gnu.tar.gz
            artifacts/i686/http-proxy-ipv6-pool_i686-unknown-linux-gnu.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
