name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install MinGW (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install mingw
          set PATH=C:\tools\mingw64\bin;%PATH%
          rustup target add x86_64-pc-windows-gnu

      - name: Verify MinGW installation (Windows only)
        if: runner.os == 'Windows'
        run: |
          gcc --version
          which x86_64-w64-mingw32-gcc

      - name: Install macOS target (macOS only)
        if: runner.os == 'macOS'
        run: |
          rustup target add x86_64-apple-darwin

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-release
          path: target/${{ matrix.target }}/release/
